### ISSUE TITLE
Variable is lost inside a loop

### ISSUE THREAD

**Issue by doctor-beat** [divengine/div#5]
Hi,

i have a question on the divengine.

When i declare a variable outside a loop then this variable appears to be gone inside the loop. Am i doing something wrong here?

`    <?
        $iterx = 999;
    ?>
    {$iterx}                 //=> output: 999
                [$matches]
                    <?
                    var_dump($iterx);    //=> output NULL
                   ?>
                [/$matches]
`

**Comment by rafageist** [comment]
Your example will output something like this

```
[[]]WARNING: Invalid macro:

var_dump($iterx);(...)

* Invalid function var_dump

999
[$matches]

[/$matches]
```

So, you need allow function `var_dump`:

```php
div::setAllowedFunction('var_dump');
```
Then the var_dump will work. This example will works:

```
{= matches: [1,2,3,4] =}
{= iterx: 999 =}
{$iterx}
[$matches]
	{$value} - {$iterx}
[/$matches]
```

Output
```
999

        1 - 999

        2 - 999

        3 - 999

        4 - 999
```
